version: '{build}'
os: Windows Server 2012

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk9
    
matrix:
  fast_finish: true

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\gradle" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://services.gradle.org/distributions/gradle-4.7-all.zip',
          'C:\gradle-all.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\gradle-all.zip", "C:\gradle")
      }
  - cmd: SET GRADLE_HOME=C:\gradle\gradle-4.7
  - cmd: SET PATH=C:\gradle\gradle-4.7\bin;%JAVA_HOME%\bin;%PATH%
#  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g

before_build:
  - choco install codecov

build_script:
  - gradle build
  
test_script:
  - gradle clean test jacocoTestReport
  - codecov -f build\reports\jacoco\full\jacocoFullReport.xml
  
  
